version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/bocchiweb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=bocchi
      - SPRING_DATASOURCE_PASSWORD=bocchi123
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=bocchiweb
      - MYSQL_USER=bocchi
      - MYSQL_PASSWORD=bocchi123
      - MYSQL_ROOT_PASSWORD=root123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./bocchiweb_db.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: